### ISSUE TITLE
Fix groundswell error in v1.3 release

### ISSUE THREAD

**Issue by gwright99** [seqeralabs/cx-field-tools-installer#114]
~I suspect the [mysql-client change](https://github.com/seqeralabs/cx-field-tools-installer/pull/107) may have broken groundswell configuration logic and that~ this is causing Tower screens to load slowly (_i.e. spinning wheel with multi-second delay_).  

~**Update 1:** I now suspect the PR isn't at fault but that something changed within Groundswell itself (_not yet confirmed, however, need @bentsherman to confirm/deny, please_).~

**Update 2:** Further investigation has revealed that the problem is tied to the [database connection string update PR](https://github.com/seqeralabs/cx-field-tools-installer/pull/86/files) that was required for `v24.1.x`, specifically how `local.tower_db_url` is generated (_and then leveraged by the [groundswell.env file generation logic](https://github.com/seqeralabs/cx-field-tools-installer/blob/master/assets/src/groundswell_config/groundswell.env.tpl#L19-L24)_). 

```bash
Jul-09 13:28:04.225 [io-executor-thread-2] 24.246.59.39 DEBUG i.s.t.s.o.GroundswellClientRetryPolicy - Checking Groundswell error result for exception [result=true]: io.micronaut.http.client.exceptions.HttpClientException: Client 'http://groundswell:8090/': Connect Error: groundswell
frontend-1        | 10.0.2.223 - - [09/Jul/2024:13:28:05 +0000] "GET /api/pipelines?orgId=11962432368870&workspaceId=139682867027751&offset=0&max=60&visibility=all&attributes=labels,computeEnv,optimized HTTP/1.1" 200 744 "https://autodc.dev-seqera.net/orgs/SampleOrg3/workspaces/SampleWorkspace/launchpad" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
backend-1         | Jul-09 13:28:05.228 [io-executor-thread-2] 24.246.59.39 DEBUG i.s.t.s.o.GroundswellClientRetryPolicy - Checking Groundswell error result for exception [result=true]: io.micronaut.http.client.exceptions.HttpClientException: Client 'http://groundswell:8090/': Connect Error: groundswell
backend-1         | Jul-09 13:28:05.228 [io-executor-thread-2] 24.246.59.39 ERROR i.s.t.s.o.OptimizationServiceImpl - Error checking optimization for pipeline [256536482607301, 140649855006943, 267379341711207, 273732561472601]
backend-1         | io.micronaut.http.client.exceptions.HttpClientException: Client 'http://groundswell:8090/': Connect Error: groundswell
backend-1         |     at io.micronaut.http.client.netty.ConnectionManager$Pool.onNewConnectionFailure(ConnectionManager.java:1033)
backend-1         |     at io.micronaut.http.client.netty.ConnectionManager$Pool.lambda$openNewConnection$0(ConnectionManager.java:1054)
backend-1         |     at io.micronaut.http.client.netty.ConnectionManager.lambda$withPropagation$6(ConnectionManager.java:573)
backend-1         |     at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
backend-1         |     at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
backend-1         |     at io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35)
backend-1         |     at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:503)
backend-1         |     at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
backend-1         |     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
backend-1         |     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
backend-1         |     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
backend-1         |     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
backend-1         |     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
backend-1         |     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
backend-1         |     at java.base/java.lang.Thread.run(Thread.java:840)
backend-1         |     Suppressed: java.lang.Exception: #block terminated with an error
backend-1         |             at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:104)
backend-1         |             at reactor.core.publisher.Flux.blockFirst(Flux.java:2766)
backend-1         |             at io.micronaut.http.client.netty.DefaultHttpClient$1.exchange(DefaultHttpClient.java:571)
backend-1         |             at io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice.lambda$handleSynchronous$1(HttpClientIntroductionAdvice.java:233)
backend-1         |             at io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice.handleBlockingCall(HttpClientIntroductionAdvice.java:620)
backend-1         |             at io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice.handleSynchronous(HttpClientIntroductionAdvice.java:232)
backend-1         |             at
```

#### TO DO:
- [ ] Modify groundswell template to only create user if not exists: `CREATE USER IF NOT EXISTS "swell" IDENTIFIED BY "swell";`
- [ ] Modify _groundswell.env.tpl_ logic for `SWELL_DB_URL`:
    - [ ] Create new local variable: `  swell_db_url = "${local.tower_db_root}/${var.swell_database_name}${data.external.generate_db_connection_string.result.value}"`
    - [ ] Make `SWELL_DB_URL` equal `local.swell_db_url`.
    - [ ] Remove if logic.

**Comment by gwright99** [comment]
Adding the following line to the `groundswell.sql.tpl` got things stable again:

```sql
GRANT ALL PRIVILEGES ON tower.* TO swell@"%";
```
