### ISSUE TITLE
Set logger levels to trace by default

### ISSUE THREAD

**Issue by gwright99** [seqeralabs/cx-field-tools-installer#17]
Tower has varying levels of logging. It would make sense to make the logging more verbose by default to make initial stand-up efforts easier to troubleshoot if there are problems.

## Values to add

- TOWER_SSH_LOGLEVEL=TRACE

Examples:
```bash
# Identify problems with SSH connections to HPC CEs
TOWER_SSH_LOGLEVEL=TRACE

Feb-02 21:39:55.023 [io-executor-thread-2] 10.42.0.1 ERROR i.s.t.c.GlobalErrorController - Oops... Unable to process request - Error ID: 5d7rDpS8pByF8YqfUVPvB4
net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
    at net.schmizz.sshj.SSHClient.auth(SSHClient.java:227)
    at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:342)
    at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:360)
    at io.seqera.tower.service.platform.ssh.SSHClientFactory.createClient(SSHClientFactory.groovy:110)
..
..
Caused by: net.schmizz.sshj.userauth.UserAuthException: Problem getting public key from PKCS5KeyFile{resource=[PrivateKeyStringResource]}
    at net.schmizz.sshj.userauth.method.KeyedAuthMethod.putPubKey(KeyedAuthMethod.java:47)
    at net.schmizz.sshj.userauth.method.AuthPublickey.buildReq(AuthPublickey.java:62)
    at net.schmizz.sshj.userauth.method.AuthPublickey.buildReq(AuthPublickey.java:81)
    at net.schmizz.sshj.userauth.method.AbstractAuthMethod.request(AbstractAuthMethod.java:68)
    at net.schmizz.sshj.userauth.UserAuthImpl.authenticate(UserAuthImpl.java:73)
    at net.schmizz.sshj.SSHClient.auth(SSHClient.java:221)
    ... 91 common frames omitted
Caused by: net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile$FormatException: Length mismatch: 1152 != 1191
    at net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile$ASN1Data.<init>(PKCS5KeyFile.java:248)
```

**Comment by gwright99** [comment]
I'm rethinking whether this is a good choice to make. 

I still think it is better to have useful logs generated **prior** to a problem rather than having to modify and try to recreate. With that said, instance logs are getting quite verbose already when only `logger.levels.com.amazonaws` is set to `DEBUG`. Adding in even more noise could make it hard to find signal amongst the noise.

Going to sit on this Issue for awhile longer and see what other folks think is an appropriate / balanced decision to take.
